services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: reality-check-elasticsearch
    environment:
      - node.name=reality-check-es
      - cluster.name=reality-check-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - reality-check-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: reality-check-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - reality-check-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: reality-check-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reality-check-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    container_name: reality-check-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379
      - GOOGLE_CLOUD_PROJECT=preplink
      - GOOGLE_CLOUD_LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - NEWS_API_KEY=9dd76ad2258b410f9cc2e33ec0487814
      - GOOGLE_SEARCH_API_KEY=AIzaSyDQ7VsFWBtTtJASFqAZqfTyFvcNkXPHt1A
      - GOOGLE_SEARCH_ENGINE_ID=2558650b2a7ea41b1
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - reality-check-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: reality-check-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - reality-check-network
    restart: unless-stopped

volumes:
  elasticsearch_data:
    driver: local
  redis_data:
    driver: local

networks:
  reality-check-network:
    driver: bridge